version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - devops-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/devops_assignment
    depends_on:
      - database
    networks:
      - devops-network

  database:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

volumes:
  mongo-data:
